version: "3"

services:
  web:
    image: okainov/mantisbt:latest
    container_name: mantis_web
    ports:
      - "8989:80"
    environment:
      - MANTIS_ENABLE_ADMIN=1
      - EMAIL_WEBMASTER=email@example.com
      - EMAIL_FROM=email@example.com
      - EMAIL_FROM_NAME=Mantis BT
      - EMAIL_RETURN_PATH=email@example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=email@example.com
      - SMTP_PASSWORD=tuntuntunsahur
      - SMTP_PORT=587
      - SMTP_MODE=tls
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantis
      - MYSQL_PASSWORD=mantis
    depends_on:
      - db
    restart: always
    networks:
      - proxy_net

  db:
    image: mysql:8.4
    container_name: mantis_db
    volumes:
      - ./db_data_v8:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantis
      - MYSQL_PASSWORD=mantis
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true