name: jenkins-docker
services:
  jenkins:
    build: .
    container_name: jenkins_app
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_net

volumes:
  jenkins-data:

networks:
  proxy_net:
    external: true